common: &common
  adapter: postgresql
  host: localhost
  username: postgres 
  password: postgres

development:
  <<: *common
  database: subdivide_development 

test:
  <<: *common
  database: subdivide_test

production:
  <<: *common
  database: subdivide_production
